import os
import sys

source = sys.argv[1]

scss_files = [f for f in os.listdir(source) if f.endswith('.scss')]

scss_files.remove('style.scss')

style_scss = open(os.path.join(source, 'style.scss'), 'w')

style_scss.write('// This file is automatically generated. Do not edit.\n\n')

for scss_file in scss_files:
    style_scss.write('@import "%s";\n' % scss_file)

style_scss.close()

# Path: .nstep\scripts\create_theme.py